from odoo import models, fields, api, _

class FPLElementSummaryHistory(models.Model):
    _name = 'fpl.element.summary.history'
    _description = 'FPL Element Summary History'

    element_id = fields.Many2one('fpl.elements', string=_('Element'))
    fixture_id = fields.Many2one('fpl.gameweek.fixtures', string=_('Fixture'))
    opponent_team = fields.Many2one('fpl.teams', string=_('Opponent Team'))
    total_points = fields.Float(string=_('Total Points'))
    was_home = fields.Boolean(string=_('Was Home'))
    kickoff_time = fields.Datetime(string=_('Kickoff Time'))
    team_h_score = fields.Integer(string=_('Team H Score'))
    team_a_score = fields.Integer(string=_('Team A Score'))
    is_modified = fields.Boolean(string=_('Modified'))
    round = fields.Integer(string=_('Round'))
    minutes = fields.Integer(string=_('Minutes'))
    goals_scored = fields.Integer(string=_('Goals Scored'))
    assists = fields.Integer(string=_('Assists'))
    clean_sheets = fields.Integer(string=_('Clean Sheets'))
    goals_conceded = fields.Integer(string=_('Goals Conceded'))
    own_goals = fields.Integer(string=_('Own Goals'))
    penalties_saved = fields.Integer(string=_('Penalties Saved'))
    penalties_missed = fields.Integer(string=_('Penalties Missed'))
    yellow_cards = fields.Integer(string=_('Yellow Cards'))
    red_cards = fields.Integer(string=_('Red Cards'))
    saves = fields.Integer(string=_('Saves'))
    bonus = fields.Integer(string=_('Bonus'))
    bps = fields.Integer(string=_('BPS'))
    influence = fields.Char(string=_('Influence'))
    creativity = fields.Char(string=_('Creativity'))
    threat = fields.Char(string=_('Threat'))
    ict_index = fields.Char(string=_('ICT Index'))
    clearances_blocks_interceptions = fields.Integer(string=_('Clearances Blocks Interceptions'))
    recoveries = fields.Integer(string=_('Recoveries'))
    tackles = fields.Integer(string=_('Tackles'))
    defensive_contribution = fields.Float(string=_('Defensive Contribution'))
    starts = fields.Integer(string=_('Starts'))
    expected_goals = fields.Char(string=_('Expected Goals'))
    expected_assists = fields.Char(string=_('Expected Assists'))
    expected_goal_involvements = fields.Char(string=_('Expected Goal Involvements'))
    expected_goals_conceded = fields.Char(string=_('Expected Goals Conceded'))
    value = fields.Integer(string=_('Value'))
    transfers_balance = fields.Integer(string=_('Transfers Balance'))
    selected = fields.Integer(string=_('Selected'))
    transfers_in = fields.Float(string=_('Transfers In'))
    transfers_out = fields.Float(string=_('Transfers Out'))
    currency_id = fields.Many2one('res.currency')
    

class FPLElementSummaryHistoryPast(models.Model):
    _name = 'fpl.element.summary.history.past'
    _description = 'FPL Element Summary History Past'

    element_id = fields.Many2one('fpl.elements', string=_('Element'))
    element_code = fields.Integer(string=_('Element Code'))
    season_name = fields.Char(string=_('Season Name'))
    start_cost = fields.Integer(string=_('Start Cost'))
    end_cost = fields.Integer(string=_('End Cost'))
    total_points = fields.Integer(string=_('Total Points'))
    minutes = fields.Integer(string=_('Minutes'))
    goals_scored = fields.Integer(string=_('Goals Scored'))
    assists = fields.Integer(string=_('Assists'))
    clean_sheets = fields.Integer(string=_('Clean Sheets'))
    goals_conceded = fields.Integer(string=_('Goals Conceded'))
    own_goals = fields.Integer(string=_('Own Goals'))
    penalties_saved = fields.Integer(string=_('Penalties Saved'))
    penalties_missed = fields.Integer(string=_('Penalties Missed'))
    yellow_cards = fields.Integer(string=_('Yellow Cards'))
    red_cards = fields.Integer(string=_('Red Cards'))
    saves = fields.Integer(string=_('Saves'))
    bonus = fields.Integer(string=_('Bonus'))
    bps = fields.Integer(string=_('BPS'))
    influence = fields.Char(string=_('Influence'))
    creativity = fields.Char(string=_('Creativity'))
    threat = fields.Char(string=_('Threat'))
    ict_index = fields.Char(string=_('ICT Index'))
    clearances_blocks_interceptions = fields.Integer(string=_('Clearances Blocks Interceptions'))
    recoveries= fields.Integer(string=_('Recoveries'))
    tackles = fields.Integer(string=_('Tackles'))
    defensive_contribution = fields.Integer(string=_('Defensive Contribution'))
    starts = fields.Integer(string=_('Starts'))
    expected_goals = fields.Char(string=_('Expected Goals'))
    expected_assists = fields.Char(string=_('Expected Assists'))
    expected_goal_involvements = fields.Char(string=_('Expected Goal Involvements'))
    expected_goals_conceded = fields.Char(string=_('Expected Goals Conceded'))
    currency_id = fields.Many2one('res.currency')

    class FplSummaryElementFixture(models.Model):
        _name = 'fpl.summary.element.fixture'

        element_id = fields.Many2one('fpl.elements')
        fixture_id = fields.Many2one('fpl.gameweek.fixtures')
        code = fields.Integer(string=_('Code'))
        team_h = fields.Many2one('fpl.teams')
        team_h_score = fields.Integer()
        team_a = fields.Many2one('fpl.teams')
        team_a_score = fields.Integer()
        event_id = fields.Many2one('fpl.events')
        finished = fields.Boolean()
        minutes = fields.Integer()
        provisional_start_time = fields.Boolean()
        kickoff_time = fields.Datetime()
        is_home = fields.Boolean()
        difficulty = fields.Integer()